kind: pipeline
name: ci

steps:
  - name: build
    image: docker
    commands:
    - docker build -t test-ntr -f Dockerfile.test .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: static code analysis
    image: docker
    commands:
      - docker run --rm test-ntr rubocop
      - docker run --rm test-ntr govuk-lint-sass app/javascript
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: security tests
    image: docker
    commands:
       - docker run --rm test-ntr bundle audit check --update
       - docker run --rm test-ntr yarn audit
       - docker run --rm test-ntr brakeman
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: unit tests
    image: docker
    commands:
    - docker run --rm test-ntr rspec -f d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: integration tests
    image: docker
    commands:
    - docker run --rm test-ntr cucumber
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - pull_request
