kind: pipeline
name: ci

steps:

  # Clean agent images and containers to prevent disk space overuse
  - name: clean-agent
    image: docker
    commands:
    - docker system prune -f
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  # Build docker image and execute tests
  - name: build-test
    image: docker
    commands:
    - docker build -t test-ntr -f Dockerfile.test .
    - docker run --rm test-ntr rspec -f d
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  # Invoke terraform scripts to ensure ecr is available for deploy step.
  - name: initialise-ecr
    image: hashicorp/terraform:0.12.3
    commands:
      - git clone https://github.com/InformedSolutions/JAQU-CAZ-IAC.git
      - cd JAQU-CAZ-IAC/terraform/projects/ntr-web/environments/dev
      - terraform init
      - terraform workspace select dev || terraform workspace new dev
      - terraform apply -target=module.ecr -auto-approve
    environment:
      TF_VAR_access_key:
        from_secret: aws_access_key_id
      TF_VAR_secret_key:
        from_secret: aws_secret_access_key

  # Push built image to ECR registry
  - name: publish-image-to-ecr
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: 018330602464.dkr.ecr.eu-west-2.amazonaws.com/ntr-web
      registry: 018330602464.dkr.ecr.eu-west-2.amazonaws.com
      dockerfile: Dockerfile.build
      region: eu-west-2
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
      build_args:
        - secret_key_base=secret

  # Invoke terraform scripts with tagged image number
  - name: deploy
    image: hashicorp/terraform:0.12.3
    commands:
      - cd JAQU-CAZ-IAC/terraform/projects/ntr-web/environments/dev
      - terraform init
      - terraform workspace select dev
      - terraform apply -auto-approve
    environment:
      TF_VAR_build_number: ${DRONE_BUILD_NUMBER}
      TF_VAR_secret_key_base: secret
      TF_VAR_google_analytics_id: test
      TF_VAR_session_timeout: 15
      TF_VAR_taxi_phv_register_api_url: https://jaqu-caz.herokuapp.com
      TF_VAR_s3_aws_access_key_id:
        from_secret: aws_access_key_id
      TF_VAR_s3_aws_secret_access_key:
        from_secret: aws_secret_access_key
      TF_VAR_s3_aws_region: eu-west-2
      TF_VAR_s3_aws_bucket: national-taxi-register.dev
      TF_VAR_aws_cognito_user_pool_id: eu-west-2_qwb4rT9Mf
      TF_VAR_aws_cognito_client_id: 4lb9pq1hkdgkqeqh3p7mjnk57m
      TF_VAR_feedback_url: https://www.surveymonkey.co.uk/r/2T8BX2D
      TF_VAR_access_key:
        from_secret: aws_access_key_id
      TF_VAR_secret_key:
        from_secret: aws_secret_access_key

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - pull_request
