require: rubocop-rails
inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'skip']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/GuardClause:
  Enabled: false

Lint/MissingSuper:
   Enabled: false
